apiVersion: namespaceconfig.raffaelespazzoli.systems/v1alpha1
kind: NamespaceConfig
metadata:
  name: example-namespaceconfig
spec:
  # Add fields here
  selector:
    matchLabels:
      namespaceconfig: "true"
    # matchExpressions:
    # - {key: namespaceconfig, operator: In, values: ["true"]}  
  networkpolicies:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: default-deny
    spec:
      podSelector: {}
      policyTypes:
      - Ingress
