---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: namespace-configuration-controller
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - "networking.k8s.io"
  resources:
  - networkpolicies
  verbs:
  - '*'  
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - rolebindings
  - clusterrolebindings
  verbs:
  - '*'     
- apiGroups:
  - ""
  resources:
  - configmaps
  - limitranges
  - resourcequotas
  - podpresets
  - serviceaccounts
  - namespaces
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - namespaceconfig.raffaelespazzoli.systems
  resources:
  - '*'
  - namespaceconfigs
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespace-configuration-controller
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-configuration-controller
subjects:
- kind: ServiceAccount
  name: namespace-configuration-controller
  namespace: namespace-configuration-controller
roleRef:
  kind: ClusterRole
  name: namespace-configuration-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: namespace-configuration-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: namespace-configuration-controller
  template:
    metadata:
      labels:
        name: namespace-configuration-controller
    spec:
      serviceAccountName: namespace-configuration-controller
      containers:
        - name: namespace-configuration-controller
          image: quay.io/raffaelespazzoli/namespace-configuration-controller:latest
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - namespace-configuration-controller
          args:
            - '--log-level'
            - debug
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "namespace-configuration-controller"


