apiVersion: apps/v1
kind: Deployment
metadata:
  name: namespace-config
spec:
  replicas: 1
  selector:
    matchLabels:
      name: namespace-config
  template:
    metadata:
      labels:
        name: namespace-config
    spec:
      serviceAccountName: namespace-config
      containers:
        - name: namespace-config
          # Replace this with the built image name
          image: REPLACE_IMAGE
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - namespace-config
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "namespace-config"
