apiVersion: apps/v1
kind: Deployment
metadata:
  name: namespace-configuration-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: namespace-configuration-controller
  template:
    metadata:
      labels:
        name: namespace-configuration-controller
    spec:
      serviceAccountName: namespace-configuration-controller
      containers:
        - name: namespace-configuration-controller
          image: quay.io/raffaelespazzoli/namespace-configuration-controller:latest
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - namespace-configuration-controller
          args:
            - '--log-level'
            - $LOG_LEVEL
          imagePullPolicy: Always
          env:
            - name: LOG_LEVEL
              value: debug
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "namespace-configuration-controller"
