kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-configuration-controller
subjects:
- kind: ServiceAccount
  name: namespace-configuration-controller
roleRef:
  kind: ClusterRole
  name: namespace-configuration-controller
  apiGroup: rbac.authorization.k8s.io
