apiVersion: namespaceconfig.raffaelespazzoli.systems/v1alpha1
kind: NamespaceConfig
metadata:
  name: special-sa
spec:
  selector:
    matchLabels:
      special-sa: "true"
  serviceaccounts: 
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: special-sa
  rolebingings:
  - apiVersion: authorization.openshift.io/v1
    kind: RoleBinding
    metadata:
      name: special-sa-rb
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: registry-editor
    subjects:
    - kind: ServiceAccount
      name: special-sa
  clusterrolebindings:
  - apiVersion: authorization.openshift.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: special-sa-crb
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole      
      name: registry-viewer
    subjects:
    - kind: ServiceAccount
      name: special-sa   
  